import fs from 'fs/promises';
import path from 'path';
import { PluginProject, ExportConfig } from '@shared/types';

/**
 * Plugin Installer Generator
 * Generates installation packages for Windows (NSIS), macOS (PKG), and Linux (DEB/RPM)
 */

export interface InstallerConfig {
  project: PluginProject;
  exportConfig: ExportConfig;
  outputDir: string;
  installerType: 'nsis' | 'pkg' | 'deb' | 'rpm' | 'all';
  includePresets?: boolean;
  includeDocumentation?: boolean;
  createDesktopShortcut?: boolean;
  autoLaunch?: boolean;
}

export async function generatePluginInstaller(config: InstallerConfig): Promise<{
  installers: { platform: string; path: string }[];
}> {
  const installers: { platform: string; path: string }[] = [];

  if (config.installerType === 'all' || config.installerType === 'nsis') {
    const nsis = await generateWindowsInstaller(config);
    installers.push({ platform: 'Windows', path: nsis });
  }

  if (config.installerType === 'all' || config.installerType === 'pkg') {
    const pkg = await generateMacOSInstaller(config);
    installers.push({ platform: 'macOS', path: pkg });
  }

  if (config.installerType === 'all' || config.installerType === 'deb') {
    const deb = await generateDebianInstaller(config);
    installers.push({ platform: 'Linux (DEB)', path: deb });
  }

  if (config.installerType === 'all' || config.installerType === 'rpm') {
    const rpm = await generateRPMInstaller(config);
    installers.push({ platform: 'Linux (RPM)', path: rpm });
  }

  return { installers };
}

// Windows NSIS Installer
async function generateWindowsInstaller(config: InstallerConfig): Promise<string> {
  const { project, outputDir } = config;
  const pluginName = project.name.replace(/\s+/g, '');
  const installerDir = path.join(outputDir, 'installers', 'windows');
  await fs.mkdir(installerDir, { recursive: true });

  const nsisScript = generateNSISScript(config);
  const scriptPath = path.join(installerDir, 'installer.nsi');
  await fs.writeFile(scriptPath, nsisScript, 'utf-8');

  // Create build script
  const buildScript = `@echo off
echo Building Windows installer for ${project.name}...
makensis installer.nsi
echo Done! Installer created: ${pluginName}-${project.version}-Setup.exe
`;
  await fs.writeFile(path.join(installerDir, 'build.bat'), buildScript, 'utf-8');

  // Create readme
  const readme = generateInstallerReadme('Windows', config);
  await fs.writeFile(path.join(installerDir, 'README.md'), readme, 'utf-8');

  return scriptPath;
}

function generateNSISScript(config: InstallerConfig): string {
  const { project, exportConfig } = config;
  const pluginName = project.name.replace(/\s+/g, '');
  const format = exportConfig.format.toUpperCase();

  return `; NSIS Installer Script for ${project.name}
; Generated by Sound Designer

!include "MUI2.nsh"

; General
Name "${project.name}"
OutFile "${pluginName}-${project.version}-Setup.exe"
InstallDir "$PROGRAMFILES\\Common Files\\${format}"
RequestExecutionLevel admin

; Modern UI Configuration
!define MUI_ABORTWARNING
!define MUI_ICON "\${NSISDIR}\\Contrib\\Graphics\\Icons\\modern-install.ico"
!define MUI_UNICON "\${NSISDIR}\\Contrib\\Graphics\\Icons\\modern-uninstall.ico"

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Language
!insertmacro MUI_LANGUAGE "English"

; Version Information
VIProductVersion "${project.version}.0"
VIAddVersionKey "ProductName" "${project.name}"
VIAddVersionKey "CompanyName" "${project.author || 'Sound Designer'}"
VIAddVersionKey "FileDescription" "${project.description}"
VIAddVersionKey "FileVersion" "${project.version}"
VIAddVersionKey "ProductVersion" "${project.version}"

; Installer Sections
Section "Plugin Files" SecPlugin
    SetOutPath "$INSTDIR"

    ; Copy plugin files
    File /r "..\\..\\Source\\*.*"

    ; Write uninstaller
    WriteUninstaller "$INSTDIR\\Uninstall-${pluginName}.exe"

    ; Registry entries
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${pluginName}" \\
                     "DisplayName" "${project.name}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${pluginName}" \\
                     "UninstallString" "$INSTDIR\\Uninstall-${pluginName}.exe"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${pluginName}" \\
                     "DisplayVersion" "${project.version}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${pluginName}" \\
                     "Publisher" "${project.author || 'Sound Designer'}"
SectionEnd

${config.includePresets ? `
Section "Presets" SecPresets
    SetOutPath "$APPDATA\\${pluginName}\\Presets"
    File /r "..\\..\\Presets\\*.*"
SectionEnd
` : ''}

${config.includeDocumentation ? `
Section "Documentation" SecDocs
    SetOutPath "$INSTDIR\\Documentation"
    File /r "..\\..\\Documentation\\*.*"
SectionEnd
` : ''}

; Uninstaller Section
Section "Uninstall"
    Delete "$INSTDIR\\*.*"
    RMDir /r "$INSTDIR"

    ${config.includePresets ? 'RMDir /r "$APPDATA\\\\' + pluginName + '\\\\Presets"' : ''}

    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${pluginName}"
SectionEnd

; Section Descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT \${SecPlugin} "Core plugin files (required)"
    ${config.includePresets ? '!insertmacro MUI_DESCRIPTION_TEXT ${SecPresets} "Factory presets"' : ''}
    ${config.includeDocumentation ? '!insertmacro MUI_DESCRIPTION_TEXT ${SecDocs} "User manual and documentation"' : ''}
!insertmacro MUI_FUNCTION_DESCRIPTION_END
`;
}

// macOS PKG Installer
async function generateMacOSInstaller(config: InstallerConfig): Promise<string> {
  const { project, outputDir } = config;
  const pluginName = project.name.replace(/\s+/g, '');
  const installerDir = path.join(outputDir, 'installers', 'macos');
  await fs.mkdir(installerDir, { recursive: true });

  // Create package structure
  const pkgRoot = path.join(installerDir, 'pkgroot');
  const scriptsDir = path.join(installerDir, 'scripts');
  await fs.mkdir(pkgRoot, { recursive: true });
  await fs.mkdir(scriptsDir, { recursive: true });

  // Create build script
  const buildScript = generateMacOSBuildScript(config);
  const scriptPath = path.join(installerDir, 'build.sh');
  await fs.writeFile(scriptPath, buildScript, 'utf-8');
  await fs.chmod(scriptPath, '755');

  // Create distribution XML
  const distributionXML = generateDistributionXML(config);
  await fs.writeFile(path.join(installerDir, 'distribution.xml'), distributionXML, 'utf-8');

  // Create postinstall script
  const postinstall = generatePostInstallScript(config);
  await fs.writeFile(path.join(scriptsDir, 'postinstall'), postinstall, 'utf-8');
  await fs.chmod(path.join(scriptsDir, 'postinstall'), '755');

  // Create readme
  const readme = generateInstallerReadme('macOS', config);
  await fs.writeFile(path.join(installerDir, 'README.md'), readme, 'utf-8');

  return scriptPath;
}

function generateMacOSBuildScript(config: InstallerConfig): string {
  const { project, exportConfig } = config;
  const pluginName = project.name.replace(/\s+/g, '');
  const format = exportConfig.format.toUpperCase();

  return `#!/bin/bash
# macOS Installer Build Script for ${project.name}
# Generated by Sound Designer

set -e

PLUGIN_NAME="${pluginName}"
VERSION="${project.version}"
FORMAT="${format}"
PKG_ROOT="./pkgroot"
SCRIPTS_DIR="./scripts"
OUTPUT_PKG="$PLUGIN_NAME-$VERSION.pkg"

echo "Building macOS installer for $PLUGIN_NAME..."

# Create package structure
mkdir -p "$PKG_ROOT/Library/Audio/Plug-Ins/$FORMAT"
${config.includePresets ? `mkdir -p "$PKG_ROOT/Library/Application Support/$PLUGIN_NAME/Presets"` : ''}
${config.includeDocumentation ? `mkdir -p "$PKG_ROOT/Library/Documentation/$PLUGIN_NAME"` : ''}

# Copy plugin files
echo "Copying plugin files..."
# cp -R "../../Source/"* "$PKG_ROOT/Library/Audio/Plug-Ins/$FORMAT/"

${config.includePresets ? `
# Copy presets
echo "Copying presets..."
# cp -R "../../Presets/"* "$PKG_ROOT/Library/Application Support/$PLUGIN_NAME/Presets/"
` : ''}

${config.includeDocumentation ? `
# Copy documentation
echo "Copying documentation..."
# cp -R "../../Documentation/"* "$PKG_ROOT/Library/Documentation/$PLUGIN_NAME/"
` : ''}

# Build component package
echo "Building component package..."
pkgbuild --root "$PKG_ROOT" \\
         --scripts "$SCRIPTS_DIR" \\
         --identifier "com.sounddesigner.$PLUGIN_NAME" \\
         --version "$VERSION" \\
         --install-location "/" \\
         "$PLUGIN_NAME-component.pkg"

# Build distribution package
echo "Building distribution package..."
productbuild --distribution distribution.xml \\
             --resources . \\
             --package-path . \\
             "$OUTPUT_PKG"

echo "Done! Installer created: $OUTPUT_PKG"
echo ""
echo "To sign the package (requires Developer ID):"
echo "  productsign --sign 'Developer ID Installer: Your Name' $OUTPUT_PKG ${pluginName}-${project.version}-signed.pkg"
`;
}

function generateDistributionXML(config: InstallerConfig): string {
  const { project } = config;
  const pluginName = project.name.replace(/\s+/g, '');

  return `<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="1">
    <title>${project.name}</title>
    <organization>com.sounddesigner</organization>
    <domains enable_localSystem="true"/>
    <options customize="never" require-scripts="false" rootVolumeOnly="true"/>

    <welcome file="welcome.html" mime-type="text/html"/>
    <license file="LICENSE.txt" mime-type="text/plain"/>
    <conclusion file="conclusion.html" mime-type="text/html"/>

    <pkg-ref id="com.sounddesigner.${pluginName}">
        <bundle-version>
            <bundle id="com.sounddesigner.${pluginName}" CFBundleVersion="${project.version}" path=""/>
        </bundle-version>
    </pkg-ref>

    <choices-outline>
        <line choice="default">
            <line choice="com.sounddesigner.${pluginName}"/>
        </line>
    </choices-outline>

    <choice id="default"/>
    <choice id="com.sounddesigner.${pluginName}" visible="false">
        <pkg-ref id="com.sounddesigner.${pluginName}"/>
    </choice>

    <pkg-ref id="com.sounddesigner.${pluginName}" version="${project.version}">${pluginName}-component.pkg</pkg-ref>
</installer-gui-script>
`;
}

function generatePostInstallScript(config: InstallerConfig): string {
  const { project } = config;

  return `#!/bin/bash
# Post-installation script for ${project.name}

# Verify installation
echo "Verifying installation..."

# Set permissions
echo "Setting permissions..."
chmod -R 755 "/Library/Audio/Plug-Ins/"*

${config.includePresets ? `
# Set preset permissions
chmod -R 755 "/Library/Application Support/${project.name.replace(/\s+/g, '')}/Presets"
` : ''}

echo "Installation complete!"
exit 0
`;
}

// Debian Package (.deb)
async function generateDebianInstaller(config: InstallerConfig): Promise<string> {
  const { project, outputDir } = config;
  const pluginName = project.name.toLowerCase().replace(/\s+/g, '-');
  const installerDir = path.join(outputDir, 'installers', 'debian');
  await fs.mkdir(installerDir, { recursive: true });

  // Create DEBIAN directory
  const debianDir = path.join(installerDir, 'DEBIAN');
  await fs.mkdir(debianDir, { recursive: true });

  // Create control file
  const control = generateDebianControl(config);
  await fs.writeFile(path.join(debianDir, 'control'), control, 'utf-8');

  // Create postinst script
  const postinst = `#!/bin/bash
set -e
ldconfig
exit 0
`;
  await fs.writeFile(path.join(debianDir, 'postinst'), postinst, 'utf-8');
  await fs.chmod(path.join(debianDir, 'postinst'), '755');

  // Create build script
  const buildScript = `#!/bin/bash
# Debian Package Build Script for ${project.name}

set -e

PACKAGE_NAME="${pluginName}"
VERSION="${project.version}"
ARCH="amd64"

echo "Building Debian package for $PACKAGE_NAME..."

# Create package structure
mkdir -p usr/lib/lv2
${config.includePresets ? `mkdir -p usr/share/$PACKAGE_NAME/presets` : ''}
${config.includeDocumentation ? `mkdir -p usr/share/doc/$PACKAGE_NAME` : ''}

# Copy files
# cp -R ../../Source/* usr/lib/lv2/

# Build package
dpkg-deb --build . "$PACKAGE_NAME"_"$VERSION"_"$ARCH".deb

echo "Done! Package created: $PACKAGE_NAME"_"$VERSION"_"$ARCH".deb
`;
  const scriptPath = path.join(installerDir, 'build.sh');
  await fs.writeFile(scriptPath, buildScript, 'utf-8');
  await fs.chmod(scriptPath, '755');

  // Create readme
  const readme = generateInstallerReadme('Debian/Ubuntu', config);
  await fs.writeFile(path.join(installerDir, 'README.md'), readme, 'utf-8');

  return scriptPath;
}

function generateDebianControl(config: InstallerConfig): string {
  const { project } = config;
  const pluginName = project.name.toLowerCase().replace(/\s+/g, '-');

  return `Package: ${pluginName}
Version: ${project.version}
Section: sound
Priority: optional
Architecture: amd64
Depends: libc6 (>= 2.14), libstdc++6 (>= 5.2)
Maintainer: ${project.author || 'Sound Designer'} <info@sounddesigner.com>
Description: ${project.description}
 ${project.name} - Audio plugin generated by Sound Designer
 .
 This package contains the ${project.name} audio plugin.
Homepage: https://sounddesigner.com
`;
}

// RPM Package
async function generateRPMInstaller(config: InstallerConfig): Promise<string> {
  const { project, outputDir } = config;
  const pluginName = project.name.toLowerCase().replace(/\s+/g, '-');
  const installerDir = path.join(outputDir, 'installers', 'rpm');
  await fs.mkdir(installerDir, { recursive: true });

  // Create RPM spec file
  const specFile = generateRPMSpec(config);
  const specPath = path.join(installerDir, `${pluginName}.spec`);
  await fs.writeFile(specPath, specFile, 'utf-8');

  // Create build script
  const buildScript = `#!/bin/bash
# RPM Package Build Script for ${project.name}

set -e

PACKAGE_NAME="${pluginName}"
VERSION="${project.version}"

echo "Building RPM package for $PACKAGE_NAME..."

# Create RPM build structure
mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

# Copy spec file
cp ${pluginName}.spec ~/rpmbuild/SPECS/

# Create source tarball
# tar czf ~/rpmbuild/SOURCES/$PACKAGE_NAME-$VERSION.tar.gz ../../Source

# Build RPM
rpmbuild -ba ~/rpmbuild/SPECS/${pluginName}.spec

echo "Done! RPM created in ~/rpmbuild/RPMS/"
`;
  const scriptPath = path.join(installerDir, 'build.sh');
  await fs.writeFile(scriptPath, buildScript, 'utf-8');
  await fs.chmod(scriptPath, '755');

  // Create readme
  const readme = generateInstallerReadme('Fedora/RHEL', config);
  await fs.writeFile(path.join(installerDir, 'README.md'), readme, 'utf-8');

  return specPath;
}

function generateRPMSpec(config: InstallerConfig): string {
  const { project } = config;
  const pluginName = project.name.toLowerCase().replace(/\s+/g, '-');

  return `Name:           ${pluginName}
Version:        ${project.version}
Release:        1%{?dist}
Summary:        ${project.description}

License:        MIT
URL:            https://sounddesigner.com
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  gcc-c++
Requires:       glibc

%description
${project.name} - Audio plugin generated by Sound Designer
${project.description}

%prep
%setup -q

%build
# Build commands here

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{_libdir}/lv2
${config.includePresets ? `mkdir -p $RPM_BUILD_ROOT%{_datadir}/%{name}/presets` : ''}
${config.includeDocumentation ? `mkdir -p $RPM_BUILD_ROOT%{_docdir}/%{name}` : ''}

# Install files
# cp -R * $RPM_BUILD_ROOT%{_libdir}/lv2/

%files
%{_libdir}/lv2/*
${config.includePresets ? `%{_datadir}/%{name}/presets/*` : ''}
${config.includeDocumentation ? `%doc %{_docdir}/%{name}/*` : ''}

%changelog
* $(date "+%a %b %d %Y") ${project.author || 'Sound Designer'} <info@sounddesigner.com> - ${project.version}-1
- Initial package release
`;
}

// Installer README generator
function generateInstallerReadme(platform: string, config: InstallerConfig): string {
  const { project } = config;

  return `# ${project.name} - ${platform} Installer

## Overview

This installer package was generated by Sound Designer for ${platform}.

**Plugin Name:** ${project.name}
**Version:** ${project.version}
**Description:** ${project.description}

## Building the Installer

${platform === 'Windows' ? `
### Windows (NSIS)

**Requirements:**
- NSIS (Nullsoft Scriptable Install System)
- Plugin binaries built for Windows

**Build Steps:**
1. Install NSIS from https://nsis.sourceforge.io/
2. Run \`build.bat\`
3. Installer will be created as \`${project.name.replace(/\s+/g, '')}-${project.version}-Setup.exe\`

**Customization:**
Edit \`installer.nsi\` to customize:
- Installation directory
- Included components
- UI appearance
- Registry entries
` : ''}

${platform === 'macOS' ? `
### macOS (PKG)

**Requirements:**
- Xcode Command Line Tools
- Plugin binaries built for macOS
- Developer ID certificate (for signing)

**Build Steps:**
1. Run \`./build.sh\`
2. Package will be created as \`${project.name.replace(/\s+/g, '')}-${project.version}.pkg\`
3. (Optional) Sign the package with your Developer ID

**Customization:**
- Edit \`build.sh\` for file locations
- Edit \`distribution.xml\` for package metadata
- Add \`welcome.html\` and \`conclusion.html\` for custom installer UI
` : ''}

${platform === 'Debian/Ubuntu' ? `
### Debian/Ubuntu (DEB)

**Requirements:**
- dpkg-deb
- Plugin binaries built for Linux

**Build Steps:**
1. Run \`./build.sh\`
2. Package will be created as \`${project.name.toLowerCase().replace(/\s+/g, '-')}_${project.version}_amd64.deb\`

**Installation:**
\`\`\`bash
sudo dpkg -i ${project.name.toLowerCase().replace(/\s+/g, '-')}_${project.version}_amd64.deb
\`\`\`

**Customization:**
Edit \`DEBIAN/control\` to modify package metadata
` : ''}

${platform === 'Fedora/RHEL' ? `
### Fedora/RHEL (RPM)

**Requirements:**
- rpmbuild
- Plugin binaries built for Linux

**Build Steps:**
1. Run \`./build.sh\`
2. Package will be created in \`~/rpmbuild/RPMS/\`

**Installation:**
\`\`\`bash
sudo rpm -i ${project.name.toLowerCase().replace(/\s+/g, '-')}-${project.version}-1.x86_64.rpm
\`\`\`

**Customization:**
Edit \`${project.name.toLowerCase().replace(/\s+/g, '-')}.spec\` to modify package metadata
` : ''}

## Installer Contents

- **Plugin Files:** Core audio plugin
${config.includePresets ? '- **Presets:** Factory presets and patches' : ''}
${config.includeDocumentation ? '- **Documentation:** User manual and guides' : ''}

## Support

For issues or questions, visit: https://sounddesigner.com/support

---

Generated by Sound Designer v${project.version}
`;
}
